<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{D20EAE72-C053-4C2C-877F-53F3F53FD1F8}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>AR_ApartmentBase</RootNamespace>
    <AssemblyName>AR_ApartmentBase</AssemblyName>
    <TargetFrameworkVersion>v4.5.1</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <TargetFrameworkProfile />
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <UseVSHostingProcess>true</UseVSHostingProcess>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AcadLib">
      <HintPath>..\..\..\AcadLib\AcadLib\bin\Release\AcadLib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcCoreMgd, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.Core.20.0.1\lib\45\AcCoreMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcCui, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AcCui.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcDbMgd, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.Model.20.0.1\lib\45\AcDbMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="acdbmgdbrep, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.Model.20.0.1\lib\45\acdbmgdbrep.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcDx, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AcDx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcMgd, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AcMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcMr, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AcMr.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcTcMgd, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AcTcMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcWindows, Version=20.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AcWindows.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AdWindows, Version=5.2.10.200, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoCAD.NET.20.0.1\lib\45\AdWindows.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AutoCAD_PIK_Manager">
      <HintPath>..\..\..\AutoCAD_PIK_Manager\AutoCAD_PIK_Manager\bin\Release\AutoCAD_PIK_Manager.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="EPPlus">
      <HintPath>..\..\..\Package\Excel\EPPlus.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Commands.cs" />
    <Compile Include="Logger.cs" />
    <Compile Include="Model\AcadServices\LayerService.cs" />
    <Compile Include="Model\DB\DataSet.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>DataSet.xsd</DependentUpon>
    </Compile>
    <Compile Include="Model\DB\DbServices\TypeConverter.cs" />
    <Compile Include="Model\DB\ExportDB.cs" />
    <Compile Include="Model\DB\Form1.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Model\DB\Form1.Designer.cs">
      <DependentUpon>Form1.cs</DependentUpon>
    </Compile>
    <Compile Include="Model\Revit\Apartment.cs" />
    <Compile Include="Model\Export\ExcelLog.cs" />
    <Compile Include="Model\Export\FormBlocksExport.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Model\Export\FormBlocksExport.Designer.cs">
      <DependentUpon>FormBlocksExport.cs</DependentUpon>
    </Compile>
    <Compile Include="Model\Revit\Elements\Element.cs" />
    <Compile Include="Model\Revit\Elements\ElemntFactory.cs" />
    <Compile Include="Model\Revit\IRevitBlock.cs" />
    <Compile Include="Model\Revit\Module.cs" />
    <Compile Include="Model\Revit\Parameter.cs" />
    <Compile Include="Model\Options.cs" />
    <Compile Include="Model\Revit\Elements\Wall.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
    <None Include="AutoCADNetLoad.scr" />
    <None Include="Model\DB\DataSet.xsc">
      <DependentUpon>DataSet.xsd</DependentUpon>
    </None>
    <None Include="Model\DB\DataSet.xsd">
      <SubType>Designer</SubType>
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DataSet.Designer.cs</LastGenOutput>
    </None>
    <None Include="Model\DB\DataSet.xss">
      <DependentUpon>DataSet.xsd</DependentUpon>
    </None>
    <None Include="Model\Revit\ClassDiagramRevit.cd" />
    <None Include="Model\Revit\Graph1.dgml" />
    <None Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Model\DB\Form1.resx">
      <DependentUpon>Form1.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Model\Export\FormBlocksExport.resx">
      <DependentUpon>FormBlocksExport.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Include="Resources\Show.png" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>